version: '3'
services:
  web:
    image: node
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  console:
    image: node
    command: bash -c 'npm install -g create-react-app && /bin/bash'
    working_dir: /app
    volumes:
      - .:/app
